openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: localhost
    url: http://localhost:3002/api/
info:
  description: Microservice d'authentification pour le jeu Loldle online
  version: "1.0.0"
  title: Loldle online authentification
  contact:
    email: jean-yves.legras@universite-paris-saclay.fr
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: player
    description: API pour gérer les joueurs inscrits et les connexion
paths:
  /api/player/login:
    post:
      tags:
        - player
      summary: Connecter un joueur existant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                mdp:
                  type: string
              required:
                - id
                - mdp
      responses:
        '200':
          description: Succès
        '400':
          description: Mauvais arguments
        '401':
          description: Mauvais mot de passe
        '404':
          description: Id non trouvé
        '500':
          description: Erreur interne

  /api/player/sign_up:
    post:
      tags:
        - player
      summary: Créer un nouveau joueur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                mdp:
                  type: string
                pseudo:
                  type: string
              required:
                - id
                - mdp
                - pseudo
      responses:
        '200':
          description: Succès
        '400':
          description: Mauvais arguments OU id déjà utilisé
        '500':
          description: Erreur interne